# helper_code/outputs.R
# Writing the master table (CSV + styled workbook), the Ensembl/symbol lists, the
# unmapped report, and the source-version manifest; plus a quality-control report with
# hard sanity-gene checks.

# Per-source gene counts, in display order.
count_genes_per_source <- function(kinases_table) {
  tibble(
    source = c("pkinfam","Manning (kinase.com)","KinHub","GO kinase activity",
               "HGNC EC 2.7","UniProt KW-0418","IDG dark kinome"),
    n = c(sum(kinases_table$is_pkinfam), sum(kinases_table$is_manning), sum(kinases_table$is_kinhub),
          sum(kinases_table$is_go_kinase_activity), sum(kinases_table$is_ec_kinase),
          sum(kinases_table$is_uniprot_kw_kinase), sum(kinases_table$is_idg_dark_kinase)))
}

# Machine-readable column contract for human_kinases_master.csv, regenerated each build so the
# schema is versioned alongside the table. Logical and categorical columns carry their allowed
# value set; everything else is declared by type only.
build_master_schema_yaml <- function(kinases_table, pipeline_version = "unversioned") {
  enum_columns <- c("kinase_type", "evidence_tier")
  r_type <- function(column) {
    if (is.logical(column)) "logical"
    else if (is.integer(column)) "integer"
    else if (is.numeric(column)) "double"
    else "character"
  }
  column_blocks <- map(names(kinases_table), \(column_name) {
    column <- kinases_table[[column_name]]
    block  <- c(sprintf("  - name: %s", column_name),
                sprintf("    type: %s", r_type(column)))
    if (is.logical(column)) {
      # readr::write_csv emits logicals as TRUE/FALSE, so the enum matches the CSV text exactly.
      c(block, '    enum: ["FALSE", "TRUE"]')
    } else if (column_name %in% enum_columns) {
      allowed <- sort(unique(column[!is.na(column) & column != ""]))
      c(block, sprintf("    enum: [%s]", paste(sprintf('"%s"', allowed), collapse = ", ")))
    } else {
      block
    }
  })
  c("# Column contract for human_kinases_master.csv",
    "# Generated by build_kinases.R -- do not edit by hand.",
    sprintf("schema_version: v%s", pipeline_version),
    "table: human_kinases_master.csv",
    "columns:",
    list_c(column_blocks))
}

write_outputs <- function(kinases_table, unmapped_table, output_dir, source_manifest,
                          build_date, pipeline_version = "unversioned") {
  master_csv_path <- file.path(output_dir, "human_kinases_master.csv")
  # Text outputs are written first and are deterministic (stable row order from classify_kinases'
  # arrange(), no embedded build date); they are byte-identical across runs on identical cached
  # inputs. The .xlsx below embeds the build date and zip timestamps and is NOT byte-stable.
  write_csv(kinases_table, master_csv_path)
  write_lines(kinases_table$ensembl_gene_id, file.path(output_dir, "kinases_ensembl_all.txt"))
  write_lines(kinases_table$ensembl_gene_id[kinases_table$protein_kinase],
              file.path(output_dir, "kinases_ensembl_protein.txt"))
  # "highconf" list = the curated-core (strict-mode) population: genes with >=1 independent
  # evidence axis (expert catalog or protein-EC), i.e. evidence_tier != Provisional.
  write_lines(kinases_table$ensembl_gene_id[kinases_table$curated_core],
              file.path(output_dir, "kinases_ensembl_highconf.txt"))
  write_lines(kinases_table$hgnc_symbol, file.path(output_dir, "kinases_symbols_all.txt"))
  write_lines(kinases_table$hgnc_symbol[kinases_table$protein_kinase],
              file.path(output_dir, "kinases_symbols_protein.txt"))
  write_csv(distinct(unmapped_table), file.path(output_dir, "kinases_unmapped.csv"))

  # Tag the build: pipeline version (single source of truth = CITATION.cff) plus a content hash
  # of the master table, so a citation can reference a fixed, verifiable build. Recorded as an
  # extra manifest row and on the workbook README sheet.
  master_content_md5 <- unname(tools::md5sum(master_csv_path))
  build_metadata_row <- tibble(
    source  = "Build (this pipeline)",
    file    = "human_kinases_master.csv",
    version = paste0("v", pipeline_version, " | md5:", master_content_md5),
    fetched = as.character(build_date),
    url     = "https://github.com/MEladawi/Kinases-List-Curation")
  source_manifest <- bind_rows(source_manifest, build_metadata_row)
  write_tsv(source_manifest, file.path(output_dir, "source_versions.tsv"))
  write_lines(build_master_schema_yaml(kinases_table, pipeline_version),
              file.path(output_dir, "schema.yaml"))

  type_counts   <- kinases_table |> count(kinase_type, sort = TRUE)
  source_counts <- count_genes_per_source(kinases_table)

  workbook <- createWorkbook()
  addWorksheet(workbook, "Kinases")
  writeData(workbook, "Kinases", kinases_table, withFilter = TRUE)
  freezePane(workbook, "Kinases", firstActiveRow = 2)
  addStyle(workbook, "Kinases",
           createStyle(fontName = "Arial", fontSize = 10, textDecoration = "bold",
                       fontColour = "white", fgFill = "#1F3864", halign = "left", border = "Bottom"),
           rows = 1, cols = seq_len(ncol(kinases_table)), gridExpand = TRUE)
  addStyle(workbook, "Kinases", createStyle(fontName = "Arial", fontSize = 10),
           rows = 2:(nrow(kinases_table) + 1), cols = seq_len(ncol(kinases_table)),
           gridExpand = TRUE, stack = TRUE)
  setColWidths(workbook, "Kinases", cols = seq_len(ncol(kinases_table)), widths = "auto")

  addWorksheet(workbook, "README")
  readme_lines <- c(
    paste("Human kinase reference table  |  build date:", build_date),
    "Key column: ensembl_gene_id (base, unversioned).",
    "",
    "BUILD:",
    sprintf("  pipeline version ........... v%s", pipeline_version),
    sprintf("  human_kinases_master.csv md5  %s", master_content_md5),
    "",
    "SOURCES (version / fetched):",
    sprintf("  %-42s %s  [fetched %s]",
            source_manifest$source, source_manifest$version, source_manifest$fetched),
    "",
    "METHOD:",
    "  Membership = union of seven legs, each mapped to Ensembl through HGNC",
    "  (the GO leg is already Ensembl-keyed). Genes are typed by FUNCTION: a gene",
    "  with a non-protein GO kinase activity is typed non-protein ONLY IF it is not",
    "  in GO:0004672 (protein kinase activity). This gate classifies e.g.",
    "  PI4KA/SPHK1/DGKA as lipid kinases but PRKCA/ATM/MTOR/PIK3CA as protein",
    "  kinases. Non-protein priority: lipid > inositol-phosphate > carbohydrate >",
    "  nucleotide > creatine, then an EC-subclass fallback. EC kinase subclasses:",
    "  2.7.1-4,6,9-14 (2.7.5/2.7.7/2.7.8 excluded).",
    "",
    "COLUMN NOTES:",
    "  is_* ................ binary membership in each source (filter per source).",
    "  kinase_group ........ UniProt -> KinHub -> kinase.com (UniProt token kept only",
    "                        if it is a real Manning group; non-protein kinases get none).",
    "  kinase_family ....... Manning short tier (Akt, CDK ...): KinHub -> kinase.com.",
    "  derived_family ...... NON-Manning fallback for genes with no kinase_family: a high-",
    "                        level descriptor from the UniProt family string, else GO class.",
    "  kinase_subfamily .... UniProt -> KinHub -> kinase.com.",
    "  uniprot_protein_family : raw UniProt 'Protein families' string.",
    "  protein_kinase ...... TRUE for protein kinases; FALSE for small-molecule",
    "                        kinases (lipid / sugar / nucleotide / etc.).",
    "  n_independent_evidence_axes : count of genuinely independent evidence authorities",
    "                        (curated expert catalog; IUBMB protein-EC). 0-2. The rigor metric.",
    "  curated_core ........ n_independent_evidence_axes >= 1 (in an expert catalog or carrying",
    "                        a protein-EC number). This is the strict-mode population.",
    "  go_experimental ..... TRUE if the gene has non-electronic (experimental/curated) GO",
    "                        kinase-activity support (no-IEA GMT). Provenance, not counted.",
    "  evidence_tier ....... practical prioritization heuristic over the independent axes plus",
    "                        experimental GO support. Gold (both axes) > Silver (one axis +",
    "                        go_experimental) > Bronze (one axis) > Provisional (neither axis).",
    "                        Not a probability, not an evidence count, not a confidence score.",
    "  dual_protein_and_nonprotein : protein kinase that also has a non-protein",
    "                        kinase function (e.g. PI3K family, NME).",
    "",
    "COUNTS BY kinase_type:",
    sprintf("  %-34s %d", type_counts$kinase_type, type_counts$n),
    "",
    "GENES PER SOURCE:",
    sprintf("  %-22s %d", source_counts$source, source_counts$n))
  writeData(workbook, "README", tibble(README = readme_lines))
  setColWidths(workbook, "README", cols = 1, widths = 95)
  saveWorkbook(workbook, file.path(output_dir, "human_kinases_master.xlsx"), overwrite = TRUE)
}

# Check the sanity genes (the cases the functional gate must get right) and, when
# verbose, print the QC summary. Returns TRUE if every sanity gene passed.
qc_report <- function(kinases_table, unmapped_table, verbose = TRUE, go_protein_kinase_n = NA_integer_) {
  emit <- function(...) if (verbose) cat(...)

  emit("\n==================== QC REPORT ====================\n")
  emit(sprintf("Total genes ............ %d\n", nrow(kinases_table)))
  if (!is.na(go_protein_kinase_n))
    emit(sprintf("GO:0004672 set size .... %d (protein kinase activity; ancestor-propagated)\n",
                 go_protein_kinase_n))
  emit(sprintf("Protein kinases ........ %d\n", sum(kinases_table$protein_kinase)))
  emit(sprintf("Non-protein kinases .... %d\n", sum(!kinases_table$protein_kinase)))
  tier_levels <- c("Gold", "Silver", "Bronze", "Provisional")
  tier_counts <- table(factor(kinases_table$evidence_tier, levels = tier_levels))
  emit(sprintf("Evidence tier .......... Gold %d | Silver %d | Bronze %d | Provisional %d\n",
               tier_counts[["Gold"]], tier_counts[["Silver"]],
               tier_counts[["Bronze"]], tier_counts[["Provisional"]]))
  emit(sprintf("Curated core (strict) .. %d\n", sum(kinases_table$curated_core)))
  emit(sprintf("Dual (protein+nonprot).. %d\n", sum(kinases_table$dual_protein_and_nonprotein)))
  emit(sprintf("Pseudogenes ............ %d\n", sum(kinases_table$is_pseudogene)))
  emit(sprintf("Unmapped (reported) .... %d\n", nrow(distinct(unmapped_table))))
  if (verbose) {
    cat("\nGenes per source:\n");      print(count_genes_per_source(kinases_table))
    cat("\nCounts by kinase_type:\n"); print(count(kinases_table, kinase_type, sort = TRUE), n = Inf)
  }

  # `go_canary` genes are typed protein kinase SOLELY on GO:0004672 evidence: NME1 is absent
  # from pkinfam/Manning/KinHub, and POMK's EC 2.7.1.183 is a non-protein subclass. If either
  # fails, the likely cause is a GO release change (the gate's GO input), not a code regression.
  sanity_genes <- tribble(
    ~symbol,  ~expected_type,                 ~expected_protein_kinase, ~go_canary,
    "PI4KA",  "Lipid kinase",                 FALSE, FALSE,
    "SPHK1",  "Lipid kinase",                 FALSE, FALSE,
    "DGKA",   "Lipid kinase",                 FALSE, FALSE,
    "HK1",    "Carbohydrate/sugar kinase",    FALSE, FALSE,
    "AK1",    "Nucleotide/nucleoside kinase", FALSE, FALSE,
    "PIK3CA", "Protein kinase",               TRUE,  FALSE,
    "NME1",   "Protein kinase",               TRUE,  TRUE,
    "ATM",    "Protein kinase",               TRUE,  FALSE,
    "MTOR",   "Protein kinase",               TRUE,  FALSE,
    "PRKCA",  "Protein kinase",               TRUE,  FALSE,
    "TRIB1",  "Protein kinase",               TRUE,  FALSE,
    "CASK",   "Protein kinase",               TRUE,  FALSE,
    "POMK",   "Protein kinase",               TRUE,  TRUE,
    "FAM20C", "Protein kinase",               TRUE,  FALSE)
  emit("\nSanity genes (* = GO:0004672-dependent canary):\n"); all_passed <- TRUE
  go_canary_failed <- FALSE
  for (i in seq_len(nrow(sanity_genes))) {
    gene_row <- kinases_table[toupper(kinases_table$hgnc_symbol) == toupper(sanity_genes$symbol[i]), ]
    passed <- nrow(gene_row) == 1 &&
              gene_row$kinase_type[1] == sanity_genes$expected_type[i] &&
              gene_row$protein_kinase[1] == sanity_genes$expected_protein_kinase[i]
    all_passed <- all_passed && passed
    if (!passed && sanity_genes$go_canary[i]) go_canary_failed <- TRUE
    emit(sprintf("  [%s] %-7s%s %-30s %s\n", if (passed) "PASS" else "FAIL", sanity_genes$symbol[i],
                 if (sanity_genes$go_canary[i]) "*" else " ",
                 if (nrow(gene_row)) gene_row$kinase_type[1] else "ABSENT",
                 if (nrow(gene_row)) gene_row$protein_kinase[1] else ""))
  }
  # --- class-level invariants: whole-family rules single-gene tests would miss ---------
  # Each rule selects a family from the columns already in the table, asserts the family is
  # non-empty (so a column rename can't make the test vacuously pass), and asserts a property
  # holds for every member.
  uniprot_family_is <- function(pattern)
    str_detect(coalesce(kinases_table$uniprot_protein_family, ""), regex(pattern, ignore_case = TRUE))
  manning_protein_groups <- c("AGC", "CAMK", "CK1", "CMGC", "NEK", "RGC", "STE", "TK", "TKL")
  class_invariants <- list(
    list(label = "Manning protein-group genes are protein kinases",
         in_family = kinases_table$kinase_group %in% manning_protein_groups,
         holds     = function(rows) all(rows$protein_kinase)),
    list(label = "Hexokinase-family genes are not protein kinases",
         in_family = uniprot_family_is("hexokinase") |
                     kinases_table$hgnc_symbol %in% c("HK1", "HK2", "HK3", "HKDC1", "GCK"),
         holds     = function(rows) all(!rows$protein_kinase)),
    # DGKQ is a genuine dual lipid+protein kinase (GO:0004697), so the rule is "no DGK is a
    # PURE protein kinase" -- every member is lipid-typed or flagged dual, never protein-only.
    list(label = "DGK-family genes are never pure protein kinases (lipid or dual)",
         in_family = str_detect(kinases_table$hgnc_symbol, "^DGK") |
                     uniprot_family_is("diacylglycerol kinase"),
         holds     = function(rows) all(!rows$protein_kinase | rows$dual_protein_and_nonprotein)))

  emit("\nClass-level invariants:\n")
  invariant_results <- map_lgl(class_invariants, \(invariant) {
    family_rows <- kinases_table[invariant$in_family, ]
    passed <- nrow(family_rows) > 0 && invariant$holds(family_rows)
    emit(sprintf("  [%s] %-58s (n=%d)\n", if (passed) "PASS" else "FAIL",
                 invariant$label, nrow(family_rows)))
    passed
  })
  all_passed <- all_passed && all(invariant_results)

  emit(sprintf("\nSanity check: %s\n", if (all_passed) "ALL PASS" else "FAILURES ABOVE"))
  if (go_canary_failed)
    emit("  NOTE: a GO:0004672-dependent canary (NME1/POMK) failed -- this is likely a GO\n",
         "        release change feeding the functional gate, not a code regression.\n")
  all_passed
}
